# Generated by Django 5.0.2 on 2024-02-23 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carname', models.CharField(max_length=255)),
                ('carburent', models.CharField(max_length=63)),
                ('price_per_day', models.FloatField(default=0)),
                ('plate', models.CharField(max_length=63, unique=True)),
                ('image', models.ImageField(default='media/photos/default.jpg', upload_to='media/photos/')),
                ('info', models.CharField(max_length=4095)),
                ('occupied', models.BooleanField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_request',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('car_id', models.CharField(max_length=63)),
                ('user_id', models.CharField(max_length=63)),
                ('accepted', models.BooleanField(default=False)),
                ('resolved', models.BooleanField()),
            ],
        ),
    ]
