# Generated by Django 5.0.2 on 2024-02-14 16:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='cin',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AddField(
            model_name='profile',
            name='cin_image',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media/ids'), upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=54),
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=51),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='', max_length=51),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
