# Generated by Django 5.0.2 on 2024-02-23 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0002_alter_car_request_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_request',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='car_request',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
