# Generated by Django 5.0.2 on 2024-02-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0002_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
