# Generated by Django 5.0.2 on 2024-02-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
