# Generated by Django 5.0.2 on 2024-02-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0004_alter_car_request_car_id_alter_car_request_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_request',
            name='car_id',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='car_request',
            name='user_id',
            field=models.CharField(max_length=63),
        ),
    ]
