# Generated by Django 5.0.2 on 2024-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0004_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=63, primary_key=True, serialize=False, unique=True),
        ),
    ]
