# Generated by Django 5.0.2 on 2024-02-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0005_remove_car_id_alter_car_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
