# Generated by Django 5.0.2 on 2024-02-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carsite', '0006_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carname', models.CharField(max_length=255)),
                ('carburent', models.CharField(max_length=63)),
                ('price_per_day', models.FloatField()),
                ('plate', models.CharField(max_length=63, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='media/photos/')),
                ('info', models.CharField(max_length=4095)),
                ('occupied', models.BooleanField()),
            ],
        ),
    ]
