# Generated by Django 5.0.2 on 2024-02-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0006_alter_car_request_car_id_alter_car_request_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_request',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='car_request',
            old_name='user_id',
            new_name='user',
        ),
    ]
