# Generated by Django 5.0.2 on 2024-03-22 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0007_rename_car_id_car_request_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_2',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='media/photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_3',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='media/photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_4',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='media/photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_5',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='media/photos/'),
        ),
        migrations.AddField(
            model_name='car_request',
            name='days_rented',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car_request',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='car_request',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car_request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='car_request',
            name='finish_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car_request',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
