# Generated by Django 5.0.2 on 2024-03-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0008_car_image_2_car_image_3_car_image_4_car_image_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='media/photos/default.png', upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='media/photos/'),
        ),
    ]
