# Generated by Django 5.0.2 on 2024-02-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0009_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.FloatField(blank=True),
        ),
    ]
