# Generated by Django 5.0.2 on 2024-02-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0010_alter_car_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.FloatField(default=0),
        ),
    ]
