# Generated by Django 5.0.2 on 2024-02-17 22:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0011_alter_car_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
