# Generated by Django 5.0.2 on 2024-02-17 22:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsite', '0012_car_id_alter_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
