# Generated by Django 5.0.2 on 2024-02-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
