# Generated by Django 5.0.2 on 2024-02-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_alter_user_cin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin_image',
            field=models.ImageField(blank=True, upload_to='media/ids/'),
        ),
    ]
