# Generated by Django 5.0.2 on 2024-02-17 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0003_alter_user_cin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
